### ISSUE TITLE
Bypass isn't shown correct

### ISSUE THREAD

**Issue by BlackAlpha700** [pravussum/openhab2-addons#4]
Switching the bypass via openHAB works fine but if the bypass was switched via air dial, the item hasn't been correctly updated.

**Comment by pravussum** [comment]
Hm, sorry but I can't reproduce the issue. Just switched Bypass on and off in the air dial and both changes got reflected in openhab. 
What's your air unit model? I've got a w2/a2.
What I can see is that the bypass status is read as boolean but in Asbjorns Google sheet its actually a byte, so maybe there are more bypass states than on and off? What options do you have in the air dial?
Do you have the software installed? What does that report as bypass state? Is it a boolean there as well?
Questions, questions ;-)

**Comment by BlackAlpha700** [comment]
Sorry, actually I'm not at home. So I'm not able to try this before Tuesday. :-(
I have an air unit w2.

But I looked at my notes (as I got them from Leaxi) and how I'd been reading the bypass in my little tool:
Adress: 0x01 0x04 0x14 0x60
Returns: 1 Byte, 0x00 = off, 0xff = on

This worked fine for me.

**Comment by pravussum** [comment]
The register is the same. Just the first bit is uses, but if release 0xff is returned for activated bypass that should be ok as well.
Maybe I have to extend the logging.

**Comment by BlackAlpha700** [comment]
Hey @pravussum ,
sorry, I was very busy the last 2 weeks and had forgotten to verify my bypass problem. I'll try it this evening when I'm at home and will send you further informations.

**Comment by BlackAlpha700** [comment]
Sorry, I don't know, what happened 2 weeks ago, but now everything works fine. I think this issue can be closed.

**Comment by pravussum** [comment]
right answer ;-)
