### ISSUE TITLE
Feature request: Night cooling

### ISSUE THREAD

**Issue by BlackAlpha700** [pravussum/openhab2-addons#7]
It would be nice to have the night cooling also controllable in the binding. :-)

**Comment by BlackAlpha700** [comment]
Sorry, maybe I'm blind or stupid... ;-)
But where could I find the release as a binary?

**Comment by pravussum** [comment]
On the releases page.
https://github.com/pravussum/openhab2-addons/releases/tag/untagged-55fe9e3ee216fc568b09

**Comment by BlackAlpha700** [comment]
The newest release shown is alpha3. That's the reason I asked you. ;-)
Opening the link above shows a "Error 404".

**Comment by pravussum** [comment]
Ah, I see. Saving the release draft failed yesterday, so it was still in draft state. It's published now, you should be able to access it. Thanks for the hint!

**Comment by BlackAlpha700** [comment]
Now I've got a release notification from github, too! Download works and a night cooling channel is found, too. Thank you for your good work again! 👍 👍 👍

**Comment by pravussum** [comment]
Cool 👍
