### ISSUE TITLE
Connection problems after switching air unit power off and on again

### ISSUE THREAD

**Issue by BlackAlpha700** [pravussum/openhab2-addons#9]
## Expected Behavior
After powering the air unit off for a while (maybe hours or days) and then powering it on again while openHAB and Danfoss-Binding are running all the time, the binding should reconnect to the air unit when it is available again.

## Current Behavior
After powering the air unit off for a while (maybe hours or days) and then powering it on again while openHAB and Danfoss-Binding are running all the time, the binding doesn't reconnect to the air unit when it is available again and you have to restart openHAB

## Steps to Reproduce (for Bugs)
1. Start openHAB
2. Switch the air unit power off (pull the plug ;-) )
3. Wait some hours or days
4. Switch the air unit on again

## Your Environment
* Version used: openHAB2.4, danfossair_alpha4
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): Ubuntu Server 18.10

**Comment by pravussum** [comment]
Fixed with d95836c115b32dfa558cdbf11e3b9ef8ce49b286
